services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs
      - flask
      - koa

  nodejs:
    image: node:alpine
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    ports:
      - "8001:3000"
    volumes:
      - ./node-app:/home/app
    depends_on:
      - php
    command: ["npm", "run", "start:dev"]

  php:
    image: webdevops/php-apache-dev:8.2
    volumes:
      - ./php-app:/app
    ports:
      - "8002:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/public

  flask:
    image: python:3.8
    working_dir: /home/app
    restart: always
    ports:
      - "8003:5000"
    volumes:
      - ./flask-app:/home/app
    depends_on:
      - php
    command: >
      bash -c "pip install -r /home/app/requirements.txt && python /home/app/app.py"

  koa:
    image: node:alpine
    working_dir: /home/app
    restart: always
    ports:
      - "8005:3000"
    volumes:
      - ./koa-app:/home/app
    depends_on:
      - php
    command: ["npm", "run", "start"]
